// Context de cada tema per al tutor. Resum fidel del llibre (McGraw-Hill,
// Física 1r Batxillerat, unitats 0 i 1) escrit per orientar el xat, no per
// substituir-lo. Les claus coincideixen amb els ids dels temes a web/index.html.

export const TOPICS = {
  inici: {
    title: "Visió general del curs",
    context: `L'alumna acaba de començar. Explica-li com està organitzada la web (Unitat 0: magnituds i mesura; Unitat 1: cinemàtica en una dimensió; Eines: derivada i trigonometria) i ajuda-la a decidir per on començar segons el que li costa.`
  },
  pendol: {
    title: "Pràctica de laboratori: el pèndol i la mesura de g",
    context: `Un pèndol simple és una massa penjada d'un fil de longitud r. El període T és el temps d'una oscil·lació completa (anar i tornar). Resultat clau de la pràctica: el període NO depèn de la massa ni, per a angles petits (menys de 10°), de l'angle inicial; només depèn de la longitud del fil. Llei: T = 2π·√(r/g). Per mesurar bé el període es cronometren 10 oscil·lacions i es divideix per 10 (T = t/10), perquè així l'error de reflexos (uns 0,2 s) es divideix entre deu. Elevant al quadrat: T² = (4π²/g)·r, és a dir T² és directament proporcional a r: el gràfic T²-r és una recta que passa per l'origen i el pendent val 4π²/g. D'aquí g = 4π²/K, on K = T²/r. Exemple: fil de 60 cm, 10 oscil·lacions en 15,5 s → T = 1,55 s; K = 1,55²/0,60 = 4,00 s²/m; g = 39,48/4,00 = 9,87 m/s². El procediment del llibre fa servir longituds de 30, 60 i 90 cm, dues esferes d'acer de masses diferents i angles de 5° i 10°, i demana omplir una taula amb T i calcular els quocients K₁, K₂, K₃. Errors habituals: comptar mitja oscil·lació, usar angles grans, mesurar el fil sense arribar al centre de l'esfera, i no passar els cm a metres.`
  },
  potencies: {
    title: "Eina: potències de 10, notació científica i calculadora",
    context: `Notació científica: un nombre entre 1 i 10 multiplicat per una potència de 10 (5,97·10^24 kg; 1,6·10^-19 C). L'exponent indica quants llocs es mou la coma: positiu cap a la dreta, negatiu cap a l'esquerra. Regles: multiplicar → es multipliquen els nombres i se sumen els exponents; dividir → es divideixen els nombres i es resten els exponents; elevar → s'eleva el nombre i es multiplica l'exponent; sumar o restar → cal primer el mateix exponent, i llavors només se sumen els nombres (els exponents no es toquen). Si el resultat no queda entre 1 i 10 cal ajustar-lo (45,2·10^20 = 4,52·10^21). Calculadora: tecla EXP, EE o ×10^x; per a 5,97·10^24 es prem 5,97 EXP 24 sense escriure "× 10" (es multiplicaria dues vegades); per als exponents negatius s'usa la tecla (−) o +/−, no la resta. Ordre de magnitud: només l'exponent, serveix per comparar ràpidament i per fer estimacions. Exemples del llibre: (5,2·10^15)(8,7·10^5) = 4,52·10^21; (3,6·10^7)(1,2·10^-4)/(6,3·10^-3) = 6,86·10^5.`
  },
  aillar: {
    title: "Eina: aïllar una incògnita i equacions de segon grau",
    context: `Una equació és una balança: el que es fa a un costat es fa a l'altre. Regles pràctiques: el que suma passa restant; el que multiplica passa dividint; el que està al quadrat passa com a arrel (de tota l'expressió); l'arrel passa com a quadrat. Ordre: desfer primer el que està més lluny de la incògnita. Exemples: de v = v₀ + a·t surt t = (v − v₀)/a; de v² = v₀² + 2·a·Δx surt Δx = (v² − v₀²)/(2·a); de T = 2π√(r/g) surt g = 4π²·r/T². Quan la incògnita apareix al quadrat i també sola (típicament la t a x = x₀ + v₀·t + ½·a·t²) és una equació de segon grau: es deixa igualada a zero, a·t² + b·t + c = 0, i s'aplica t = (−b ± √(b² − 4ac))/(2a). Surten dues solucions i sovint una és un temps negatiu, que es descarta perquè seria abans de començar el problema. Exemple: pilota llançada cap amunt a 10 m/s des de 20 m: 0 = 20 + 10t − 4,9t² → 4,9t² − 10t − 20 = 0 → t = 3,28 s (l'altra, −1,24 s, es descarta). Consell: aïllar amb lletres primer i substituir els números al final. Error freqüent: √(a² + b²) no és a + b.`
  },
  problemes: {
    title: "Eina: com atacar un problema de cinemàtica",
    context: `Mètode de sis passos: (1) llegir dues vegades i fer un dibuix (recta, mòbil, fletxes); (2) posar l'origen i decidir el sentit positiu (en caigudes, positiu cap amunt i origen a terra); (3) apuntar les dades amb signe i en unitats del SI, passant km/h a m/s abans de res, i afegint les dades amagades a l'enunciat ("parteix del repòs" és v₀ = 0; "s'atura" és v = 0; "arriba a terra" és y = 0; "cau lliurement" és a = g); (4) escriure què demanen amb la seva lletra; (5) triar la fórmula que conté la incògnita i que només necessita dades conegudes (si hi apareix una lletra que ni es té ni es busca, no és aquesta); (6) substituir, calcular i comprovar unitats, signe i si el número és raonable. Les quatre fórmules del curs: MRU x = x₀ + v·t; MRUA v = v₀ + a·t, x = x₀ + v₀·t + ½·a·t², i v² = v₀² + 2·a·Δx (aquesta quan no hi ha temps). Exemple complet: cotxe a 72 km/h que frena amb 4 m/s², distància fins a aturar-se: v₀ = 20 m/s, a = −4 m/s², v = 0, busquem Δx → v² = v₀² + 2aΔx → Δx = 400/8 = 50 m.`
  },
  magnituds: {
    title: "Magnituds físiques i mesura",
    context: `Una magnitud física és qualsevol propietat d'un cos o fenomen que es pot mesurar i expressar amb un nombre (massa, longitud, temps, velocitat, temperatura). Coses com l'alegria o la bellesa no són magnituds perquè no es poden quantificar objectivament. Mesurar és comparar una magnitud amb una altra de la mateixa espècie que prenem com a unitat (el valor 1). Tota mesura s'escriu com valor + unitat: 180 cm, 14 s, 80 km/h. Un nombre sense unitat no diu res en física. Mesurament directe: es fa amb un instrument (regle, balança, cronòmetre). Mesurament indirecte: es calcula a partir d'altres mesures directes (l'àrea d'un rectangle S = a·b; la velocitat mitjana v = Δx/Δt). Només es poden sumar o restar magnituds iguals (metres amb metres); multiplicar i dividir sí que es pot entre magnituds diferents (m/s). Anàlogament, les magnituds es divideixen en escalars (només valor: temperatura, temps, massa) i vectorials (valor, direcció i sentit: força, velocitat, desplaçament).`
  },
  si: {
    title: "El Sistema Internacional, prefixos i factors de conversió",
    context: `El Sistema Internacional (SI) fixa set magnituds fonamentals amb les seves unitats: longitud (metre, m), massa (quilogram, kg), temps (segon, s), intensitat de corrent (ampere, A), temperatura (kelvin, K), quantitat de substància (mol), intensitat lluminosa (candela, cd). Des del 2018 totes es defineixen a partir de constants universals (velocitat de la llum c, constant de Planck h, càrrega elemental e, constant de Boltzmann k, nombre d'Avogadro N_A, freqüència de transició del cesi Δν_Cs, eficàcia lluminosa K_cd) i ja no a partir de prototips com el cilindre de platí-iridi del quilogram guardat a Sèvres. Múltiples: deca (da, 10^1), hecto (h, 10^2), kilo (k, 10^3), mega (M, 10^6), giga (G, 10^9), tera (T, 10^12). Submúltiples: deci (d, 10^-1), centi (c, 10^-2), mil·li (m, 10^-3), micro (μ, 10^-6), nano (n, 10^-9), pico (p, 10^-12). Notació científica: un nombre entre 1 i 10 multiplicat per una potència de 10 (5,97·10^24 kg; 1,602·10^-19 C). Factors de conversió: fraccions que valen 1 (1 km / 1000 m; 1 h / 3600 s) que es multipliquen fins que les unitats que no volem s'anul·len. Exemple del llibre: 72 km/h · (1000 m / 1 km) · (1 h / 3600 s) = 20 m/s. Truc: km/h a m/s es divideix per 3,6. Superfície i volum: 1 m² = 10^4 cm², 1 m³ = 10^6 cm³ (l'exponent multiplica). 1 L = 1 dm³, 1 mL = 1 cm³.`
  },
  dimensional: {
    title: "Magnituds derivades i equació dimensional",
    context: `Les magnituds derivades es defineixen a partir de les fonamentals (velocitat = longitud/temps; força = massa·acceleració; densitat = massa/volum). Algunes unitats derivades tenen nom propi: newton (N = kg·m/s²), joule (J = N·m), watt (W = J/s), pascal (Pa = N/m²), coulomb (C = A·s), volt (V = J/C), hertz (Hz = s^-1). L'equació dimensional expressa una magnitud en funció de les dimensions fonamentals, escrites amb claudàtors: [L] longitud, [M] massa, [T] temps, [I] intensitat. Exemples: [v] = L·T^-1; [a] = L·T^-2; [F] = M·L·T^-2; [E] = M·L²·T^-2; [p] (pressió) = M·L^-1·T^-2; [ρ] = M·L^-3. Serveix per: (1) saber en quines unitats del SI s'expressa una magnitud, (2) comprovar si una fórmula pot ser correcta: els dos membres d'una equació han de tenir la mateixa equació dimensional (principi d'homogeneïtat). Que sigui homogènia és necessari però no suficient perquè sigui correcta (una constant numèrica com 1/2 no té dimensions). Exemple del llibre: [E_c] = [1/2·m·v²] = M·L²·T^-2. Els angles i les magnituds com el coeficient de fregament no tenen dimensions.`
  },
  vectors: {
    title: "Magnituds vectorials: el vector i les seves components",
    context: `Magnituds escalars: queden determinades amb un nombre i una unitat (temperatura, massa, temps, energia). Magnituds vectorials: a més del valor cal saber la direcció i el sentit (velocitat, força, desplaçament, acceleració, camp elèctric). Es representen amb vectors: segments orientats. Un vector té: mòdul (longitud del segment, sempre positiu, |a| o a), direcció (la recta que el conté), sentit (cap a on apunta la fletxa, un dels dos possibles) i punt d'aplicació (origen). Vectors equipol·lents: mateix mòdul, direcció i sentit. Vectors oposats: mateix mòdul i direcció, sentit contrari (a i -a). Components cartesianes: a = (a_x, a_y), les projeccions sobre els eixos X i Y. Mòdul per Pitàgores: a = √(a_x² + a_y²). Argument (angle α amb el semieix X positiu): tg α = a_y / a_x. Coordenades polars: (mòdul, angle), s'escriu a = 5,83 (angle 59,04°). De polars a cartesianes: a_x = a·cos α, a_y = a·sin α. Vectors unitaris: mòdul 1; i = (1,0) en l'eix X, j = (0,1) en l'eix Y, k = (0,0,1) en l'eix Z. Qualsevol vector és combinació lineal: a = a_x·i + a_y·j. Exemple del llibre: a = (3,5): mòdul √(9+25) = 5,83; α = tg^-1(5/3) = 59,04°. Compte amb la calculadora: tg^-1 dona angles entre -90° i 90°; si a_x és negatiu cal sumar 180°.`
  },
  "operacions-vectors": {
    title: "Operacions amb vectors: suma, producte per escalar, vector unitari, producte escalar",
    context: `Suma de vectors per components: a + b = (a_x + b_x)·i + (a_y + b_y)·j. Gràficament, regla del paral·lelogram o posant un vector a continuació de l'altre. Resta: a - b = a + (-b). Producte d'un vector per un escalar k: k·a = (k·a_x, k·a_y); mateixa direcció, mòdul multiplicat per |k|, mateix sentit si k>0 i sentit contrari si k<0. Vector unitari d'un vector b: u_b = b / |b| (es divideix cada component pel mòdul); té mòdul 1, mateixa direcció i sentit. Exemple del llibre: c = a - 2b amb a = i - 2j i b = -3i + 2j dona c = 7i - 6j, |c| = 9,22, u_c = 0,76i - 0,65j. Producte escalar de dos vectors: a·b = |a|·|b|·cos α (α angle entre ells) i també a·b = a_x·b_x + a_y·b_y. El resultat és un escalar (un nombre), no un vector. Signe: positiu si α < 90°, zero si α = 90° (perpendiculars), negatiu si α > 90°. a·a = a². i·i = j·j = 1; i·j = 0. Angle entre dos vectors: cos α = (a_x·b_x + a_y·b_y) / (|a|·|b|). Exemple del llibre: a = 4i - 5j, b = 2i - 8j: a·b = 8 + 40 = 48; |a| = 6,40; |b| = 8,25; cos α = 0,91; α = 24,62°. Propietats: commutativa (a·b = b·a) i distributiva (a·(b+c) = a·b + a·c).`
  },
  error: {
    title: "Mesura i error: error instrumental, xifres significatives, error absolut i relatiu",
    context: `Cap mesura és exacta. Error instrumental: el valor més petit que pot apreciar l'instrument (sensibilitat). Un regle graduat en mil·límetres té sensibilitat 0,1 cm; una balança digital 0,01 g. Una mesura s'escriu valor ± error: (23,1 ± 0,1) cm. Les xifres significatives són les que aporten informació: es compten des de la primera xifra diferent de zero. 23,1 cm té tres. Els zeros a l'esquerra no compten (0,0064 té dues); els zeros a la dreta darrere la coma sí (8,0 cm té dues i vol dir que s'ha mesurat fins a la dècima). En sumar mesures, el resultat no pot tenir més decimals que la mesura amb menys decimals; en multiplicar/dividir, no més xifres significatives que la dada amb menys. Arrodonir: si la primera xifra eliminada és menor que 5 es deixa igual; si és 5 o més gran, s'augmenta una unitat l'última conservada. Error de mesura (aleatori): en repetir una mesura n vegades surten valors diferents. Procediment del llibre: (1) mitjana aritmètica m̄ = Σm_i / n; (2) error particular de cada valor e_i = |m_i - m̄|; (3) error absolut e_a = màx(e_i) (i mai més petit que l'error instrumental); (4) resultat (m̄ ± e_a) unitat; (5) error relatiu e_r = e_a / m̄ · 100 (%). L'error relatiu és el que diu si la mesura és bona: 1 cm d'error en 1 m és 1 %, però en 10 cm és 10 %. Exemple del llibre: 10 temps de caiguda entre 3,42 i 3,51 s, mitjana 3,45 s, error absolut 0,06 s, error relatiu 1,7 %. Precisió: com més xifres significatives, més precisa. Mesures directes vs indirectes (l'error es propaga).`
  },
  metode: {
    title: "El mètode científic",
    context: `El mètode científic (o experimental) consisteix en quatre fases: (1) Observació: mirar un fenomen amb atenció i fer-se preguntes. (2) Emissió d'hipòtesis: afirmacions raonades, provisionals, que intenten explicar-lo i que s'han de poder comprovar. (3) Experimentació: dissenyar un experiment en condicions controlades, canviant una sola variable cada vegada, mesurant i recollint dades en taules i gràfics. (4) Establiment d'una llei: si les dades confirmen la hipòtesi, s'enuncia una llei, sovint amb una expressió matemàtica; si la contradiuen, es refusa i es proposa una altra hipòtesi. Un conjunt de lleis que expliquen un àmbit forma una teoria científica. Exemple del llibre (densitat): observem que els objectes grans de ferro pesen més; hipòtesi: la massa és proporcional al volum per a un mateix material; experiment: mesurem massa i volum de diverses peces de ferro (0,8 cm³ → 6,24 g; 1,6 → 12,48; 2,3 → 17,94; 3,1 → 24,18); el gràfic m-V és una recta que passa per l'origen i el quocient m/V val sempre 7,8 g/cm³; llei: m = ρ·V, la densitat és una propietat característica de cada material. Idea clau: una llei no es demostra mai del tot, només es confirma mentre cap experiment la contradigui.`
  },
  moviment: {
    title: "Moviment, sistema de referència i trajectòria",
    context: `La cinemàtica estudia el moviment sense preguntar-se per les causes (això és la dinàmica). El moviment és el canvi de posició d'un cos al llarg del temps respecte a un sistema de referència. Mòbil puntual o partícula: simplificació on tota la massa del cos es concentra en un punt. El moviment és relatiu: depèn de l'observador. Un passatger assegut a l'autobús està quiet respecte al seient i es mou respecte a la carretera. No hi ha cap sistema de referència absolut. El sistema de referència sol ser un sistema d'eixos cartesians (X, Y, Z) amb un origen O i un instant inicial (t = 0). Trajectòria: la línia formada per totes les posicions per on passa el mòbil. Segons la trajectòria: moviment rectilini (línia recta, una dimensió), circular (circumferència), parabòlic (paràbola), el·líptic, helicoidal... A la unitat 1 només es tracta el moviment rectilini: tot passa sobre una recta, l'eix X, i els vectors es redueixen a un signe (+ o -) que indica el sentit.`
  },
  posicio: {
    title: "Posició, desplaçament i distància recorreguda",
    context: `Temps (t): magnitud escalar, unitat SI el segon. Interval de temps Δt = t_2 - t_1 (Δ, delta, sempre vol dir final menys inicial). Posició (x): el punt on és el mòbil en un instant determinat, mesurat des de l'origen del sistema de referència; en el pla és el vector de posició r = x·i + y·j. En moviment rectilini és un nombre amb signe: x = +3 km (a la dreta de l'origen) o x = -2 km (a l'esquerra). Equació del moviment: x(t), la posició en funció del temps. Desplaçament (Δx): canvi de posició entre dos instants, Δx = x_2 - x_1. És un vector: pot ser positiu, negatiu o zero. Distància recorreguda: la longitud real del camí seguit sobre la trajectòria; sempre positiva. Si el mòbil va i torna al mateix punt, el desplaçament és zero però la distància no. Coincideixen només si el moviment és rectilini i sempre en el mateix sentit. Exemple del llibre (caminada popular): grups que surten de la plaça (x = 0) cap a l'ermita a 5 km; el grup 4 està a 4 km i el grup 3 a 3 km; el desplaçament del grup 3 des de la sortida és 3 - 0 = 3 km; entre el grup 3 i el 4, x_2 - x_1 = 3 - 4 = -1 km si s'agafa com a inicial el 4. Compte: el desplaçament depèn només de les posicions inicial i final, no del camí.`
  },
  velocitat: {
    title: "Velocitat mitjana i velocitat instantània",
    context: `Velocitat: magnitud vectorial que mesura com canvia la posició amb el temps; unitat SI m/s. Velocitat mitjana en un interval: v_m = Δx / Δt = (x_2 - x_1)/(t_2 - t_1). És el pendent del segment (secant) que uneix dos punts del gràfic x-t. Només informa de l'interval sencer: si vas de Girona a Lleida a 80 km/h de mitjana, no vol dir que anessis sempre a 80. Velocitat mitjana vs celeritat mitjana: la velocitat mitjana usa el desplaçament (pot ser negativa o zero); la celeritat (rapidesa) mitjana usa la distància recorreguda. Velocitat instantània: la velocitat en un instant concret, la que marca el velocímetre. S'obté fent l'interval Δt cada vegada més petit: v = lim (Δt→0) Δx/Δt = dx/dt. Aquest límit és la derivada de la posició respecte del temps. Gràficament és el pendent de la recta tangent a la corba x-t en aquell instant. Signe: v > 0 el mòbil es mou en el sentit positiu de l'eix; v < 0 en sentit negatiu; v = 0 està aturat en aquell instant. Exemple del llibre (entrenament): tram 1: 1000 m en 600 s → 1,67 m/s; tram 3: Δx = 0 en 300 s → v_m = 0 (aturat o ha tornat al mateix punt); tram 5: Δx = -1500 m en 520 s → -2,88 m/s (torna enrere); global: 5000 m en 3600 s → 1,38 m/s. Conversió: km/h ÷ 3,6 = m/s.`
  },
  acceleracio: {
    title: "Acceleració",
    context: `Acceleració: magnitud vectorial que mesura com canvia la velocitat amb el temps; unitat SI m/s² (metres per segon cada segon). Acceleració mitjana: a_m = Δv / Δt = (v_2 - v_1)/(t_2 - t_1). És el pendent del gràfic v-t. Acceleració instantània: a = lim (Δt→0) Δv/Δt = dv/dt, la derivada de la velocitat (i la segona derivada de la posició). Idea clau: acceleració no vol dir "anar ràpid" sinó "canviar de velocitat". Un cotxe a 120 km/h constants té acceleració zero; un que arrenca del semàfor accelera; un que frena també té acceleració (de signe contrari a la velocitat). Signes en una dimensió: si a i v tenen el mateix signe, el mòbil va cada cop més ràpid; si tenen signes contraris, frena. Una acceleració negativa no vol dir frenar: si v també és negativa, el mòbil accelera cap a l'esquerra. Exemple: un cotxe passa de 0 a 100 km/h (27,8 m/s) en 10 s: a_m = 2,78 m/s². Caiguda lliure: a = g = 9,8 m/s² cap avall.`
  },
  mru: {
    title: "Moviment rectilini uniforme (MRU)",
    context: `MRU: trajectòria recta i velocitat constant (mòdul, direcció i sentit). Acceleració zero. En intervals de temps iguals recorre distàncies iguals. Equació del moviment: x = x_0 + v·t (posició inicial x_0, velocitat v, temps t des de t = 0). Si el temps no comença a zero: x = x_0 + v·(t - t_0). Gràfic x-t: una recta el pendent de la qual és la velocitat (pendent positiu, es mou en sentit positiu; negatiu, en sentit negatiu; horitzontal, aturat). Gràfic v-t: recta horitzontal; l'àrea sota la recta entre dos instants és el desplaçament (v·Δt). Gràfic a-t: a = 0 sempre. Exemples quotidians aproximats: un tren en un tram recte a velocitat de creuer, una cinta transportadora, la llum (3·10^8 m/s). Problema típic de trobada: dos mòbils amb x_A(t) i x_B(t); es troben quan x_A = x_B; igualem i aïllem t. Cal el mateix origen, el mateix instant inicial i les mateixes unitats per als dos.`
  },
  mrua: {
    title: "Moviment rectilini uniformement accelerat (MRUA)",
    context: `MRUA: trajectòria recta i acceleració constant. La velocitat canvia sempre al mateix ritme. Equacions: v = v_0 + a·t; x = x_0 + v_0·t + (1/2)·a·t²; i la que elimina el temps: v² = v_0² + 2·a·(x - x_0) = v_0² + 2·a·Δx. Gràfic v-t: recta de pendent a; l'àrea sota la recta és el desplaçament. Gràfic x-t: paràbola (cap amunt si a > 0, cap avall si a < 0); el pendent en cada punt és la velocitat instantània. Gràfic a-t: recta horitzontal. Si v_0 i a tenen el mateix signe el mòbil accelera; si són de signe contrari frena fins a v = 0 i, si continua, inverteix el sentit. Exemple: cotxe que frena de 20 m/s amb a = -4 m/s²: s'atura en t = 5 s i recorre Δx = (0 - 400)/(2·(-4)) = 50 m. Distància de frenada: proporcional a v², per això doblar la velocitat quadruplica la distància per aturar-se. Consell: fer sempre un esquema, fixar l'origen i el sentit positiu, escriure les dades amb signe i unitats del SI abans de substituir.`
  },
  caiguda: {
    title: "Caiguda lliure i llançament vertical",
    context: `Caiguda lliure: moviment d'un cos sota l'acció exclusiva de la gravetat (sense fregament amb l'aire). És un MRUA amb a = g = 9,8 m/s² dirigida cap avall, igual per a tots els cossos independentment de la massa (Galileu: una ploma i un martell cauen igual al buit). Convenció habitual: eix Y positiu cap amunt, origen a terra; llavors a = -9,8 m/s². Equacions: v = v_0 - g·t; y = y_0 + v_0·t - (1/2)·g·t²; v² = v_0² - 2·g·(y - y_0). Deixar caure: v_0 = 0. Llançament vertical cap amunt: v_0 > 0; puja frenant fins a v = 0 al punt més alt (t_pujada = v_0/g; alçada màxima h = v_0²/(2g)), després baixa accelerant; torna a la mateixa alçada amb la mateixa velocitat en mòdul però sentit contrari; el temps de pujada és igual al de baixada. Al punt més alt v = 0 però a = -g (no és zero!). Exemple: pedra que cau des de 20 m: t = √(2h/g) = 2,02 s; arriba a terra a 19,8 m/s (71 km/h). Exemple: pilota llançada cap amunt a 10 m/s: puja 5,1 m, triga 1,02 s a pujar i 2,04 s a tornar a la mà.`
  },
  grafics: {
    title: "Llegir i dibuixar gràfics x-t, v-t i a-t",
    context: `Els gràfics resumeixen tot el moviment. Gràfic x-t (posició-temps): el pendent en cada punt és la velocitat; recta = velocitat constant; horitzontal = aturat; corba = velocitat que canvia (paràbola en MRUA); pendent positiu = avança en sentit positiu; pendent negatiu = retrocedeix. Compte: el gràfic x-t NO és un dibuix de la trajectòria. Gràfic v-t (velocitat-temps): el pendent és l'acceleració; l'àrea entre la corba i l'eix de temps és el desplaçament (àrea per sota de l'eix compta negativa); horitzontal = MRU; recta inclinada = MRUA; el mòbil canvia de sentit quan la corba talla l'eix (v = 0). Gràfic a-t: l'àrea és el canvi de velocitat Δv. Regla ràpida: baixar un nivell (x→v→a) és derivar (pendent); pujar-ne un (a→v→x) és integrar (àrea). Exemple del llibre (mètode científic): gràfic m-V que és una recta per l'origen, i el pendent és la densitat: la proporcionalitat directa sempre dona una recta que passa per l'origen.`
  },
  derivada: {
    title: "Eina: què és una derivada (sense por)",
    context: `A física la derivada apareix perquè volem saber com de ràpid canvia una cosa en un instant. La velocitat mitjana és un quocient d'increments Δx/Δt: el pendent d'una secant entre dos punts del gràfic. Si acostem els dos punts (Δt → 0) la secant es converteix en la tangent i el quocient tendeix a un valor: la derivada dx/dt, la velocitat instantània. Derivada = pendent de la tangent = ritme de canvi instantani. Notació: v = dx/dt (Leibniz) o x'(t). Regles bàsiques que surten al curs: la derivada d'una constant és 0; la derivada de k·t és k; la derivada de t² és 2t; la derivada de t^n és n·t^(n-1); la derivada d'una suma és la suma de derivades. Aplicació directa: si x = x_0 + v_0·t + (1/2)·a·t², derivant surt v = v_0 + a·t, i derivant un altre cop surt a. El procés invers (de l'acceleració a la velocitat o de la velocitat a la posició) és calcular una àrea sota el gràfic: la integral. Exemples quotidians: el velocímetre del cotxe és una derivada; el comptaquilòmetres és una integral; la factura de la llum és una integral de la potència.`
  },
  trigo: {
    title: "Eina: trigonometria per als vectors",
    context: `Per descompondre un vector fa falta el triangle rectangle. Si un vector de mòdul a forma un angle α amb l'eix X: la component horitzontal és a_x = a·cos α (el catet adjacent a l'angle) i la vertical a_y = a·sin α (el catet oposat). tg α = a_y / a_x, i per recuperar l'angle, α = tg^-1(a_y/a_x). Pitàgores: a² = a_x² + a_y². Valors que convé tenir al cap: sin 0° = 0, cos 0° = 1; sin 30° = 0,5, cos 30° = 0,87; sin 45° = cos 45° = 0,71; sin 60° = 0,87, cos 60° = 0,5; sin 90° = 1, cos 90° = 0. Truc de memòria: el cosinus va amb l'eix X ("costat"), el sinus va amb l'eix Y. Compte amb la calculadora: que estigui en graus (DEG), no en radians. Quadrants: si a_x < 0 la calculadora dona l'angle equivocat en tg^-1; cal sumar 180°. Exemple: vector de mòdul 10 a 30°: a_x = 8,66, a_y = 5. Exemple invers: (−3, 4): mòdul 5, tg^-1(4/−3) = −53,1°, i com que a_x < 0, α = 126,9°.`
  }
};
